# Generated by Django 5.1.3 on 2024-12-05 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planta',
            name='qr_code',
            field=models.ImageField(default='qr_codes/default_qr.png', upload_to=''),
        ),
    ]
