# Generated by Django 5.1.2 on 2024-12-05 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_planta_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planta',
            name='especie',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='planta',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='planta',
            name='tamano',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='planta',
            name='tipoluz',
            field=models.CharField(max_length=20),
        ),
    ]
